### PR TITLE
Use PrettyTable with GitHub policy

### PR DESCRIPTION
**Pull request by jeromecoutant**
This is following discussion in https://github.com/ARMmbed/greentea/issues/277

### CODE REVIEW

**Comment by jeromecoutant** [comment]
For information, here is all related PR :

- https://github.com/ARMmbed/mbed-os/pull/7720
- https://github.com/ARMmbed/greentea/pull/279
- https://github.com/ARMmbed/mbed-ls/pull/383
- https://github.com/ARMmbed/htrun/pull/208

**Comment by theotherjimmy** [comment]
@jeromecoutant It looks like a test case is asserting on some output that you're changing here. Could you update that test case too?

**Comment by theotherjimmy** [comment]
@bridadan Do you foresee any issues that could be caused by merging this? I want to take it.

**Comment by bridadan** [comment]
Don't think so, but could someone post a before and after console output?

**Comment by cmonr** [comment]
@bridadan A reference output can be found here: https://github.com/ARMmbed/mbed-os/pull/7720#issue-206694528

**Comment by jeromecoutant** [comment]
Hi
For information, this is not in a released version. Is it planned ?
Thx

**Comment by cmonr** [comment]
@jeromecoutant https://github.com/ARMmbed/greentea/releases

Sorry, we haven't made a greentea release since this came in. It will be in the next release.

**Pull request merged**
