### PR TITLE
set forced_reset_timeout 10 sec for RAPIDIOT_K64F

### PR DESCRIPTION
**Pull request by studavekar**
RAPIDIOT_K64F devices take a longer time to boot up.

### CODE REVIEW

**Comment by studavekar** [comment]
cc: @maclobdell

**Comment by maclobdell** [comment]
cc @mmahadevan108 
please review.  
please note that this requires updating your greentea version used for testing.  we will do a separate pr for updating mbed-os to require the latest greentea (and other test related) python modules.

**Comment by bridadan** [comment]
@studavekar @maclobdell Is the increased boot time due to the fact that the interface chip queries the MCU first? Htrun currently sets a default `forced_reset_timeout` of 1 second. 10 seconds is an order of magnitude increase, so it'd be good to make sure its absolutely necessary!

**Comment by maclobdell** [comment]
@bridadan - the rapid Iot platform is unique.  It has a bootloader that interrogates the contents of a spi flash to check if a newer application is available for each processor (K41Z & K64F).  This takes a few seconds.  I agree that 10 seconds might be too long to wait and could blow up the test time to epic proportions of there is some fundamental problem.  @mmahadevan108 - Can you suggest a more appropriate timeout for this target?  Will it be guaranteed to boot the application within 3 sec, 4 sec, 5 sec?

**Comment by mmahadevan108** [comment]
Thank you, this change will work for RapidIoT

**Comment by theotherjimmy** [comment]
@mmahadevan108, @maclobdell was asking if 10 sec is really required as this will greatly slow down the Mbed OS CI. Each test will wait an additional 10 seconds, which especially harms tests that take <1 sec (a good portion of the tests). Our CI runtime is predicted by the longest time it takes for a platform to run all of it's tests, so we're wondering if we can safely save a few seconds * number of tests (100s) for this platform.

**Comment by mmahadevan108** [comment]
From my testing, forced_reset_timeout of 5 secs did not work. 
6 secs upwards worked. I would suggest we go with 7 secs.

**Comment by studavekar** [comment]
@mmahadevan108 thanks will set it to 7 secs

**Pull request merged**
