### PR TITLE
Passing mbed target id to htrun in cmd line arguments

### PR DESCRIPTION
**Pull request by mazimkhan**
In support of https://github.com/ARMmbed/htrun/pull/75 to pass target id while launching htrun

### CODE REVIEW

**Comment by mazimkhan** [comment]
CI failing because of coveralls

**Comment by stegut01** [comment]
+1

**Comment by PrzemekWirkus** [comment]
Please rebase, I pushed with ```--force``` to Greentea master branch and stuff happened... Sorry about that.

**Comment by mazimkhan** [comment]
@PrzemekWirkus rebase done.

**Pull request merged**
