### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by AnotherButler**
- @bridadan's content changes [delete outdated docs folder, update docs for content]
- Make minor grammar, spelling and style changes for consistency

### CODE REVIEW

**Comment by AnotherButler** [comment]
@iriark01 @adbridge

**Comment by iriark01** [comment]
Where are we with this? Are we still considering adding it to the handbook?

**Comment by AnotherButler** [comment]
Yes. I was waiting for the PR to be merged before moving it to the Handbook.

**Comment by iriark01** [comment]
Right. I think you already told me that. Sorry.

**Comment by bridadan** [comment]
Bumpity bump @mazimkhan @adbridge!

**Comment by AnotherButler** [comment]
@mazimkhan @adbridge Please let me know if there's anything I can do to help get this merged or if there are any problems with it that are preventing it from getting merged. Thanks so much.

**Comment by bridadan** [comment]
Same from me! Let's get this in!

**Comment by mazimkhan** [comment]
Sorry I am not up to date with this. Where are the contents of ```CONTRIBUTING.md``` and ```docs/CONTRIBUTING.md``` gone. Also the ```QUICKSTART.md``` still talks about yotta!

**Comment by bridadan** [comment]
@mazimkhan the contents of both `CONTRIBUTING` docs were both pretty out of date and also had some pretty bad grammar. For this reason @AnotherButler and I thought it made sense to remove them. Do we really have to have a contributing doc?

We also removed the `QUICKSTART` doc entirely in this PR, so where are you seeing the yotta mentions?

**Comment by mazimkhan** [comment]
I see. GitHib wasn't loading quickstart.md so I clicked it and saw yotta. But yes it is removed.
It is fine with me. I don't think we need an elaborate CONTRIBUTING.md. But it would good have something generic. That explains process for open source contributions into this repo. Or if have a common for mbed-os we can point to that.

**Comment by bridadan** [comment]
@mazimkhan Keeping the CONTRIBUTING.md file is ok with me, but we should create a task to go back and update it with good information and better grammar :)

I've created a PR here with the update: https://github.com/ARMmbed/greentea/pull/217

@AnotherButler, if you're happy with #217 would you mind closing this PR? Thanks!

**Comment by AnotherButler** [comment]
Closing in favor of #217

**Pull request closed without merging**
