### PR TITLE
Ignoring bad unicode characters

### PR DESCRIPTION
**Pull request by bridadan**
This should stop the exception occurring in #288.

### CODE REVIEW

**Comment by bridadan** [comment]
> We could also use the system default encoding, and not ignore.

I'm not as familiar with character encoding (in and out of Python) as I'd like to be, could explain that a bit more? Instead of specifying `utf-8` would it be more something like calling `sys.getdefaultencoding()` to get the right encoding?

**Comment by theotherjimmy** [comment]
@bridadan Exactly correct. `sys.getdefaultencodinfg()` is the system default encoding.

**Comment by bridadan** [comment]
Gotcha. Maybe a separate PR?

**Comment by theotherjimmy** [comment]
@bridadan It would be an alternate solution to the same problem.

**Comment by bridadan** [comment]
This PR makes the last few calls to `decode` that don't have `'ignore'` added consistent with the rest of the codebase. There other places in the codebase where we're currently doing things like `s.decode('utf-8', 'ignore')`, so I'd prefer to change all of those in one PR with some added manual testing.

**Comment by theotherjimmy** [comment]
Sounds good to me.

**Pull request merged**
