### PR TITLE
Remove traceback from parsing invalid keywords

### PR DESCRIPTION
**Pull request by theotherjimmy**

### CODE REVIEW

**Comment by theotherjimmy** [comment]
@scartmell-arm @bridadan Could you review?

**Comment by bridadan** [comment]
Do we need a test case for the case where it would return None?

**Comment by theotherjimmy** [comment]
The test case does test for returning `None`. Are you looking for a specific test case?

**Comment by bridadan** [comment]
AH yes, sorry, I was only looking at the diff.

Specifically I was wondering about the case when `keywords` and `name` are not in the JSON blob.

**Comment by bridadan** [comment]
Not sure if that's a specific case we need to enforce that it always works with a test or not.

**Comment by theotherjimmy** [comment]
That's a good test case to have. I'll write it in a moment.

**Comment by scartmell-arm** [comment]
Seems like a reasonable change.

**Comment by theotherjimmy** [comment]
** Facepalm **

I should write these tests.

**Comment by theotherjimmy** [comment]
@bridadan Your tests have arrived!

**Pull request merged**
