### PR TITLE
Preliminary port to Python 3

### PR DESCRIPTION
**Pull request by Sentimentron**
Mostly minor syntax issues and renamed imports.

### CODE REVIEW

**Comment by LiyouZhou** [comment]
Is this port backwards compatible to python2 as well?

**Comment by Sentimentron** [comment]
It passes the tests under Python 2, _but_ whilst the Python 3 syntax is fine and you can import greentea from from a dependency under Python 3, the tests themselves don't pass yet under Python 3 because mbed_host_tests hasn't been ported yet.

**Comment by theotherjimmy** [comment]
@LiyouZhou @Sentimentron See https://github.com/ARMmbed/htrun/pull/165. Would you like me to take over this PR to rebase and add testing to Travis?

**Comment by Sentimentron** [comment]
I don't have a problem with that.

**Comment by theotherjimmy** [comment]
Cool. I'll get to it now.

**Comment by theotherjimmy** [comment]
Amusingly, it looks like you run circle, in travis compatibility mode XD

**Comment by theotherjimmy** [comment]
@Sentimentron @LiyouZhou See #235

**Comment by theotherjimmy** [comment]
Closing as #235 Was merged.

**Pull request closed without merging**
