### PR TITLE
Added HTML report generation

### PR DESCRIPTION
**Pull request by ConorPKeegan**
# Changes
* Added `--report-html <filename>` switch to trigger HTML report generation
* Added the functions needed to generate HTML reports

# Usage
```
$ mbedgt -V --report-html report.html
```

# Implements
* Implemented enhancement #165 

# Example
* [report.html](https://rawgit.com/ConorPKeegan/cea0f0beee3934a9529c6d268e04e21f/raw/07c1d143f097a0607c1d2589fb99e7c260298265/report.html)

### CODE REVIEW

**Comment by ConorPKeegan** [comment]
@PrzemekWirkus @mazimkhan @adbridge 
Any comments on the style?

**Comment by PrzemekWirkus** [comment]
Tip: Conor, you can use GIST to store your HTML example and just set a link to page which will render HTML example:
* Gist of your report: https://gist.githubusercontent.com/PrzemekWirkus/af819b362fe93b28d4b0ddcac4e48ca6/raw/d01825dfdb36cb5e12af8d108739e27b12529ba8/report_1.html
* Rendered HTML of your example report: https://rawgit.com/PrzemekWirkus/af819b362fe93b28d4b0ddcac4e48ca6/raw/d01825dfdb36cb5e12af8d108739e27b12529ba8/report_1.html

All you do is to replace `gist.githubusercontent.com` with `rawgit.com` in link to RAW Gist :)

**Comment by PrzemekWirkus** [comment]
@adbridge @mazimkhan @bridadan FYI

**Comment by PrzemekWirkus** [comment]
@ConorPKeegan Plase have a look at some error codes here: https://github.com/ARMmbed/greentea/blob/master/mbed_greentea/mbed_test_api.py#L51

Please add simple data structure with HTML colors and some simple API to fetch color for each test result.

```python
# New structure with colors
TEST_RESULTS_COLORS = {
    TEST_RESULT_OK : '',
    TEST_RESULT_FAIL : '',
    TEST_RESULT_ERROR : '',
    TEST_RESULT_SKIPPED : '',
    ...
}

def get_result_colors(test_result):
    return TEST_RESULTS_COLORS.get(test_result, 'Grey')
```

We can always change colors ;-)

**Comment by ConorPKeegan** [comment]
@PrzemekWirkus @mazimkhan @adbridge @bridadan 
Here is an example with a FAIL, ERROR, and SKIPPED added:
https://rawgit.com/ConorPKeegan/cea0f0beee3934a9529c6d268e04e21f/raw/07c1d143f097a0607c1d2589fb99e7c260298265/report.html

**Comment by adustm** [comment]
Hello, @PrzemekWirkus  informed me about this new feature.
I have a question about the previous report you mentionned : 
https://rawgit.com/ConorPKeegan/cea0f0beee3934a9529c6d268e04e21f/raw/07c1d143f097a0607c1d2589fb99e7c260298265/report.html

When clicking on the error test (tests-mbedmicro-mbed-div with ARM toolchain) we cannot see that the output of the test is failed (it says Result: OK Elapsed Time: 9.53 Start Time: 01-01-1970 00:00:00.000000 End Time: 01-01-1970 00:00:00.000000 Failed: 0 Passed: 1)
Is it an error or a manual modification of the test result to show the red error button ?

Kind regards
Armelle

**Comment by PrzemekWirkus** [comment]
@adustm It is ebcause we've just changed OK/ERROR colors so we can see how different error loevels will look like. This report under the hood is all OK cases :) It is just coloring we wanted to check in this example.

**Pull request merged**
